### ISSUE TITLE
C连接层有偶尔崩溃

### ISSUE THREAD

**Issue by sdlyxcc** [GoBelieveIO/im_android#11]
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: use of deleted weak global reference 0x100487
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]     from void android.os.MessageQueue.nativePollOnce(long, int)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470] "im_service" prio=5 tid=14 Runnable
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   | group="main" sCount=0 dsCount=0 obj=0x12c8ea60 self=0x7f9e7cca00
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   | sysTid=16099 nice=0 cgrp=default sched=0/0 handle=0x7f92e1d450
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   | state=R schedstat=( 338208750 28913798 312 ) utm=13 stm=20 core=5 HZ=100
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   | stack=0x7f92d1b000-0x7f92d1d000 stackSize=1037KB
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   | held mutexes= "mutator lock"(shared held)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   native: #00 pc 00000000004cadb8  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+220)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   native: #01 pc 00000000004cadb4  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+216)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   native: #02 pc 000000000049d954  /system/lib64/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+480)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   native: #03 pc 0000000000324208  /system/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1164)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   native: #04 pc 00000000003245b8  /system/lib64/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+188)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   native: #05 pc 00000000004a234c  /system/lib64/libart.so (_ZNK3art6Thread13DecodeJObjectEP8_jobject+320)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   native: #06 pc 0000000000103cac  /system/lib64/libart.so (_ZN3art11ScopedCheck13CheckInstanceERNS_18ScopedObjectAccessENS0_12InstanceKindEP8_jobjectb+196)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   native: #07 pc 0000000000101a60  /system/lib64/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+1152)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   native: #08 pc 00000000001055a8  /system/lib64/libart.so (_ZN3art8CheckJNI6NewRefEPKcP7_JNIEnvP8_jobjectNS_15IndirectRefKindE+632)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   native: #09 pc 0000000000001768  /data/app/io.gobelieve.im.demo-2/lib/arm64/libasync_tcp.so (???)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   native: #10 pc 000000000001874c  /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+892)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   native: #11 pc 0000000000018310  /system/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+60)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   native: #12 pc 00000000000f7ad0  /system/lib64/libandroid_runtime.so (_ZN7android18NativeMessageQueue8pollOnceEP7_JNIEnvP8_jobjecti+48)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   native: #13 pc 00000000009f5dd0  /system/framework/arm64/boot-framework.oat (Java_android_os_MessageQueue_nativePollOnce__JI+140)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   at android.os.MessageQueue.nativePollOnce(Native method)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   at android.os.MessageQueue.next(MessageQueue.java:323)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   at android.os.Looper.loop(Looper.java:136)
2020-12-18 14:31:57.806 16081-16099/? A/art: art/runtime/java_vm_ext.cc:470]   at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by richmonkey** [comment]
是im_android工程吗？在im_android工程可以复现吗

**Comment by sdlyxcc** [comment]
不容易复现，是在聊完后，不操作时 偶尔崩溃了，抓的上面日志信息

**Comment by richmonkey** [comment]
是im_andorid（没有做任何修改）工程吗？停留在哪个界面（activity）？

**Comment by coscx** [comment]
这个问题我也遇到了，app退到后台 反复进行三次 第三次会闪退

**Comment by richmonkey** [comment]
因为有其它相同的issue， 所以就关掉这个issue了
