### ISSUE TITLE
运行demo闪退

### ISSUE THREAD

**Issue by ttz541** [GoBelieveIO/im_android#8]
刚安装可以运行，登录并发送接收成功。关掉再次打开会闪退，但也并不是每次都闪退。应该是获取File路径和权限不匹配。android9.0 oppo手机。

**Comment by ttz541** [comment]
2020-05-26 10:32:23.076 12206-12636/io.gobelieve.im.demo W/System.err: java.io.IOException: Couldn't open file:///storage/emulated/0/.UTSystemConfig/Global/Alvin2.xml
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at org.apache.harmony.xml.ExpatParser.openUrl(ExpatParser.java:762)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:292)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at javax.xml.parsers.SAXParser.parse(SAXParser.java:326)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.core.y.a(DeviceInfo.java:103)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.core.x.b(ClientInfo.java:277)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.core.x.a(ClientInfo.java:43)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.core.q.d_(ProtocalHandler.java:154)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.core.br.a(NetManger.java:420)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.core.br.a(NetManger.java:288)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.core.q.f(ProtocalHandler.java:87)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.core.q.g(ProtocalHandler.java:71)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.geocoder.GeocodeSearch.getFromLocation(GeocodeSearch.java:61)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.geocoder.GeocodeSearch$1.run(GeocodeSearch.java:99)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err: Caused by: java.io.FileNotFoundException: /storage/emulated/0/.UTSystemConfig/Global/Alvin2.xml (Permission denied)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at java.io.FileInputStream.open0(Native Method)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at java.io.FileInputStream.open(FileInputStream.java:231)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:165)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:112)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
2020-05-26 10:32:23.077 12206-12636/io.gobelieve.im.demo W/System.err:     at org.apache.harmony.xml.ExpatParser.openUrl(ExpatParser.java:760)
2020-05-26 10:32:23.078 12206-12636/io.gobelieve.im.demo W/System.err: 	... 14 more
2020-05-26 10:32:23.078 12206-12636/io.gobelieve.im.demo D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2020-05-26 10:32:23.083 12206-12542/io.gobelieve.im.demo W/System.err: java.io.IOException: No such file or directory
2020-05-26 10:32:23.083 12206-12542/io.gobelieve.im.demo W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
2020-05-26 10:32:23.083 12206-12542/io.gobelieve.im.demo W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
2020-05-26 10:32:23.083 12206-12542/io.gobelieve.im.demo W/System.err:     at java.io.File.createNewFile(File.java:1013)
2020-05-26 10:32:23.083 12206-12542/io.gobelieve.im.demo W/System.err:     at com.amap.api.mapcore2d.r.a(CachManager.java:319)
2020-05-26 10:32:23.083 12206-12542/io.gobelieve.im.demo W/System.err:     at com.amap.api.mapcore2d.bz.a(TileServerHandler.java:108)
2020-05-26 10:32:23.083 12206-12542/io.gobelieve.im.demo W/System.err:     at com.amap.api.mapcore2d.bz.b(TileServerHandler.java:69)
2020-05-26 10:32:23.084 12206-12542/io.gobelieve.im.demo W/System.err:     at com.amap.api.mapcore2d.bz.a(TileServerHandler.java:26)
2020-05-26 10:32:23.084 12206-12542/io.gobelieve.im.demo W/System.err:     at com.amap.api.mapcore2d.bp.b(ProtocalHandler.java:140)
2020-05-26 10:32:23.084 12206-12636/io.gobelieve.im.demo W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
2020-05-26 10:32:23.084 12206-12542/io.gobelieve.im.demo W/System.err:     at com.amap.api.mapcore2d.bp.g(ProtocalHandler.java:73)
2020-05-26 10:32:23.084 12206-12542/io.gobelieve.im.demo W/System.err:     at com.amap.api.mapcore2d.bp.a(ProtocalHandler.java:60)
2020-05-26 10:32:23.084 12206-12542/io.gobelieve.im.demo W/System.err:     at com.amap.api.mapcore2d.by.a(TileServer.java:63)
2020-05-26 10:32:23.084 12206-12542/io.gobelieve.im.demo W/System.err:     at com.amap.api.mapcore2d.k.run(AsyncServer.java:139)
2020-05-26 10:32:23.084 12206-12542/io.gobelieve.im.demo W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-05-26 10:32:23.085 12206-12636/io.gobelieve.im.demo I/System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
2020-05-26 10:32:23.086 12206-12636/io.gobelieve.im.demo W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
2020-05-26 10:32:23.087 12206-12636/io.gobelieve.im.demo I/System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
2020-05-26 10:32:23.105 12206-12636/io.gobelieve.im.demo W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
2020-05-26 10:32:23.107 12206-12636/io.gobelieve.im.demo I/System.out: [OkHttp] sendRequest>>
2020-05-26 10:32:23.108 12206-12636/io.gobelieve.im.demo I/System.out: [OkHttp] sendRequest<<
2020-05-26 10:32:23.129 12206-12636/io.gobelieve.im.demo W/System.err: com.amap.api.services.core.AMapException
2020-05-26 10:32:23.129 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.core.d.b(CoreUtil.java:67)
2020-05-26 10:32:23.129 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.core.q.a(ProtocalHandler.java:63)
2020-05-26 10:32:23.129 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.core.q.b(ProtocalHandler.java:163)
2020-05-26 10:32:23.129 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.core.q.f(ProtocalHandler.java:92)
2020-05-26 10:32:23.129 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.core.q.g(ProtocalHandler.java:71)
2020-05-26 10:32:23.129 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.geocoder.GeocodeSearch.getFromLocation(GeocodeSearch.java:61)
2020-05-26 10:32:23.129 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.geocoder.GeocodeSearch$1.run(GeocodeSearch.java:99)
2020-05-26 10:32:23.129 12206-12636/io.gobelieve.im.demo W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-05-26 10:32:23.130 12206-12636/io.gobelieve.im.demo W/System.err: com.amap.api.services.core.AMapException
2020-05-26 10:32:23.130 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.core.q.f(ProtocalHandler.java:100)
2020-05-26 10:32:23.130 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.core.q.g(ProtocalHandler.java:71)
2020-05-26 10:32:23.130 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.geocoder.GeocodeSearch.getFromLocation(GeocodeSearch.java:61)
2020-05-26 10:32:23.130 12206-12636/io.gobelieve.im.demo W/System.err:     at com.amap.api.services.geocoder.GeocodeSearch$1.run(GeocodeSearch.java:99)
2020-05-26 10:32:23.130 12206-12636/io.gobelieve.im.demo W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by richmonkey** [comment]
这是集成到自己app还是运行的原始demo？

**Comment by ttz541** [comment]
> 
> 
> 这是集成到自己app还是运行的原始demo？

是原始demo，你看上面打印出来的包名就是io.gobelieve.im.demo

**Comment by richmonkey** [comment]
发送文件已修复
